name: CI => Super-Linter Validation
on:
  pull_request:
    branches: [ "main" ]

jobs:
  super-linter:
    name: Linter Markdown
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descarga el código del PR
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Ejecuta Super-Linter (solo para Markdown)
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: .*\.md  # Solo archivos Markdown
          VALIDATE_ALL_CODEBASE: false   # Solo archivos modificados en el PR

